{"name": "test_update_contact_unauthorized_patch_method", "status": "passed", "description": "TC024: Unsuccessful update contact without auth token and \n    using PATCH method", "attachments": [{"name": "log", "source": "b0b80c69-3885-4d5c-bf05-75754064c18b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "6f082302-8613-4e1c-be47-0339c433db69-attachment.txt", "type": "text/plain"}], "start": 1733918931350, "stop": 1733918931851, "uuid": "a5b41b3b-b3ef-4c9e-bc54-1893fbaf762d", "historyId": "6bf049449559dea6bd9e39417301d5d6", "testCaseId": "6bf049449559dea6bd9e39417301d5d6", "fullName": "API.test_api#test_update_contact_unauthorized_patch_method", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "5cbf70c9ed4a"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}