{"name": "test_update_user_bad_request", "status": "skipped", "statusDetails": {"message": "XFAIL Unexpected 200 response\n\nAssertionError: assert 200 == 400\n +  where 200 = <APIResponse url='https://thinking-tester-contact-list.herokuapp.com/users/me' status=200 status_text='OK'>.status", "trace": "api_request_context = <playwright._impl._fetch.APIRequestContext object at 0x7f6f11d72e10>\nauth_token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NmMzYjM3YTY5NjBlNTAwMTNjOWY2ODIiLCJpYXQiOjE3MzM5MTg5MTJ9.m0_-IgYBfLVE4nbuCiKc9c_HANQonf_uUHmAcD2D2rw'\n\n    @pytest.mark.extended\n    @pytest.mark.API\n    @pytest.mark.xfail(reason=\"Unexpected 200 response\")\n    def test_update_user_bad_request(api_request_context:\n    APIRequestContext, auth_token):\n        \"\"\"TC008: Unsuccessful update user without body\"\"\"\n        url = \"/users/me\"\n    \n        headers = {\n            \"Authorization\": f\"Bearer {auth_token}\",\n            \"Content-Type\": \"application/json\"\n        }\n    \n        body = {}\n    \n        logger.info(\"Update user using empty body: {}.\")\n        response = api_request_context.patch(url, data=json.dumps(body),\n                                             headers=headers)\n    \n        logger.info(f\"Assert actual response code: {response.status} \"\n                    f\"with expected: 400.\")\n>       assert response.status == 400\nE       AssertionError: assert 200 == 400\nE        +  where 200 = <APIResponse url='https://thinking-tester-contact-list.herokuapp.com/users/me' status=200 status_text='OK'>.status\n\nAPI/test_api.py:587: AssertionError"}, "description": "TC008: Unsuccessful update user without body", "attachments": [{"name": "log", "source": "165ca708-0aa2-44fe-a2a4-d7b46b8e4b12-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "4c292bd3-26e0-4656-b68a-73f49b04f788-attachment.txt", "type": "text/plain"}], "start": 1733918937025, "stop": 1733918937499, "uuid": "2434420a-c9da-4f0f-9957-7fa824d777fc", "historyId": "d3b2bb415db435aa55a95e2bd5fd03da", "testCaseId": "d3b2bb415db435aa55a95e2bd5fd03da", "fullName": "API.test_api#test_update_user_bad_request", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Unexpected 200 response')"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "extended"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "5cbf70c9ed4a"}, {"name": "thread", "value": "1-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}