{"name": "test_update_contact_unauthorized_patch_method", "status": "passed", "description": "TC024: Unsuccessful update contact without auth token and \n    using PATCH method", "attachments": [{"name": "log", "source": "3088af77-afab-41a2-9e35-9b0535b571b2-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "3a2dd94a-0b35-476b-9c68-fa948fbd8601-attachment.txt", "type": "text/plain"}], "start": 1733906258576, "stop": 1733906258703, "uuid": "75a21cf4-b635-4d98-b9cd-182a47de419e", "historyId": "6bf049449559dea6bd9e39417301d5d6", "testCaseId": "6bf049449559dea6bd9e39417301d5d6", "fullName": "API.test_api#test_update_contact_unauthorized_patch_method", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-0LB7JBM"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}