{"name": "test_add_user_email_already_in_use", "status": "passed", "description": "TC002: Add User - 400 Bad request 'Email address \n    is already in use'", "attachments": [{"name": "log", "source": "098710f7-f703-44cf-b614-a4bcdaaa4485-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5ef2c04e-6dd6-44c0-95b4-afb4471328a8-attachment.txt", "type": "text/plain"}], "start": 1733906254439, "stop": 1733906254603, "uuid": "7827c6cc-8267-462f-8fe1-f369710d941d", "historyId": "14599a2bb18ecfd40de8ecf52f94eaa3", "testCaseId": "14599a2bb18ecfd40de8ecf52f94eaa3", "fullName": "API.test_api#test_add_user_email_already_in_use", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "API"}, {"name": "tag", "value": "critical"}, {"name": "parentSuite", "value": "API"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "DESKTOP-0LB7JBM"}, {"name": "thread", "value": "11428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "API.test_api"}]}